export const universitiesInTurkey = [
  {
    web_pages: ["http://www.adu.edu.tr/"],
    name: "Adnan Menderes University",
    alpha_two_code: "TR",
    domains: ["adu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ahievran.edu.tr/"],
    name: "Ahi Evran University",
    alpha_two_code: "TR",
    domains: ["ahievran.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.akdeniz.edu.tr/"],
    name: "Akdeniz University",
    alpha_two_code: "TR",
    domains: ["akdeniz.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.aku.edu.tr/"],
    name: "Afyon Kocatepe University",
    alpha_two_code: "TR",
    domains: ["aku.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.anadolu.edu.tr/"],
    name: "Anadolu University",
    alpha_two_code: "TR",
    domains: ["anadolu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ankara.edu.tr/"],
    name: "Ankara University",
    alpha_two_code: "TR",
    domains: ["ankara.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.arel.edu.tr/"],
    name: "Istanbul Arel University",
    alpha_two_code: "TR",
    domains: ["arel.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.atauni.edu.tr/"],
    name: "Atatürk University",
    alpha_two_code: "TR",
    domains: ["atauni.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.atilim.edu.tr/"],
    name: "Atilim University",
    alpha_two_code: "TR",
    domains: ["atilim.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.bahcesehir.edu.tr/"],
    name: "Bahcesehir University",
    alpha_two_code: "TR",
    domains: ["bahcesehir.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.balikesir.edu.tr/"],
    name: "Balikesir University",
    alpha_two_code: "TR",
    domains: ["balikesir.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.baskent.edu.tr/"],
    name: "Baskent University",
    alpha_two_code: "TR",
    domains: ["baskent.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.mcbu.edu.tr/", "http://www.cbu.edu.tr/"],
    name: "Celal Bayar University",
    alpha_two_code: "TR",
    domains: ["mcbu.edu.tr", "cbu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.beykent.edu.tr/"],
    name: "Beykent University",
    alpha_two_code: "TR",
    domains: ["beykent.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.bilecik.edu.tr/"],
    name: "Bilecik University",
    alpha_two_code: "TR",
    domains: ["bilecik.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.bilgi.edu.tr/"],
    name: "Istanbul Bilgi University",
    alpha_two_code: "TR",
    domains: ["bilgi.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.bilkent.edu.tr/"],
    name: "Bilkent University",
    alpha_two_code: "TR",
    domains: ["bilkent.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.boun.edu.tr/"],
    name: "Boğaziçi University",
    alpha_two_code: "TR",
    domains: ["boun.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.cag.edu.tr/"],
    name: "Cag University",
    alpha_two_code: "TR",
    domains: ["cag.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.cankaya.edu.tr/"],
    name: "Cankaya University",
    alpha_two_code: "TR",
    domains: ["cankaya.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.comu.edu.tr/"],
    name: "Canakkale (18th March) University",
    alpha_two_code: "TR",
    domains: ["comu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.cu.edu.tr/"],
    name: "Cukurova University",
    alpha_two_code: "TR",
    domains: ["cu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.cumhuriyet.edu.tr/"],
    name: "Cumhuriyet (Republik) University",
    alpha_two_code: "TR",
    domains: ["cumhuriyet.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.deu.edu.tr/"],
    name: "Dokuz Eylül University",
    alpha_two_code: "TR",
    domains: ["deu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.dho.edu.tr/"],
    name: "Turkish Naval Academy",
    alpha_two_code: "TR",
    domains: ["dho.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.dicle.edu.tr/"],
    name: "Dicle (Tirgris) University",
    alpha_two_code: "TR",
    domains: ["dicle.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.dogus.edu.tr/"],
    name: "Dogus University",
    alpha_two_code: "TR",
    domains: ["dogus.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.dumlupinar.edu.tr/", "http://www.dpu.edu.tr/"],
    name: "Dumlupinar University",
    alpha_two_code: "TR",
    domains: ["dumlupinar.edu.tr", "dpu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ege.edu.tr/"],
    name: "Ege University",
    alpha_two_code: "TR",
    domains: ["ege.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.erciyes.edu.tr/"],
    name: "Erciyes University",
    alpha_two_code: "TR",
    domains: ["erciyes.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.etu.edu.tr/"],
    name: "Tobb Economics and Technology University",
    alpha_two_code: "TR",
    domains: ["etu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.firat.edu.tr/"],
    name: "Firat (Euphrates) University",
    alpha_two_code: "TR",
    domains: ["firat.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["https://fbu.edu.tr/"],
    name: "Fenerbahce University",
    alpha_two_code: "TR",
    domains: ["fbu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.gantep.edu.tr/"],
    name: "Gaziantep University",
    alpha_two_code: "TR",
    domains: ["gantep.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.gazi.edu.tr/"],
    name: "Gazi University Ankara",
    alpha_two_code: "TR",
    domains: ["gazi.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.gop.edu.tr/"],
    name: "Gaziosmanpasa University",
    alpha_two_code: "TR",
    domains: ["gop.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.gsu.edu.tr/"],
    name: "Galatasaray University",
    alpha_two_code: "TR",
    domains: ["gsu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.gyte.edu.tr/"],
    name: "Gebze Institute of Technology",
    alpha_two_code: "TR",
    domains: ["gyte.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.halic.edu.tr/"],
    name: "Halic University",
    alpha_two_code: "TR",
    domains: ["halic.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.harran.edu.tr/"],
    name: "Harran University",
    alpha_two_code: "TR",
    domains: ["harran.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.hun.edu.tr/", "http://www.hacettepe.edu.tr/"],
    name: "Hacettepe University",
    alpha_two_code: "TR",
    domains: ["hun.edu.tr", "hacettepe.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ibu.edu.tr/"],
    name: "Abant Izzet Baysal University",
    alpha_two_code: "TR",
    domains: ["ibu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.iku.edu.tr/"],
    name: "Istanbul Kultur University",
    alpha_two_code: "TR",
    domains: ["iku.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.inonu.edu.tr/"],
    name: "Inönü University",
    alpha_two_code: "TR",
    domains: ["inonu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.isikun.edu.tr/"],
    name: "Isik University",
    alpha_two_code: "TR",
    domains: ["isikun.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.iticu.edu.tr/"],
    name: "Istanbul Ticaret University",
    alpha_two_code: "TR",
    domains: ["iticu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.itu.edu.tr/"],
    name: "Istanbul Technical University",
    alpha_two_code: "TR",
    domains: ["itu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.iyte.edu.tr/"],
    name: "Izmir Institute of Technology",
    alpha_two_code: "TR",
    domains: ["iyte.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.izmirekonomi.edu.tr/"],
    name: "Izmir Economic University",
    alpha_two_code: "TR",
    domains: ["izmirekonomi.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.kafkas.edu.tr/"],
    name: "Kafkas University",
    alpha_two_code: "TR",
    domains: ["kafkas.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.karaelmas.edu.tr/"],
    name: "Zonguldak Karaelmas University",
    alpha_two_code: "TR",
    domains: ["karaelmas.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.khas.edu.tr/"],
    name: "Kadir Has University",
    alpha_two_code: "TR",
    domains: ["khas.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.kilis.edu.tr/"],
    name: "Kilis 7 Aralık University",
    alpha_two_code: "TR",
    domains: ["kilis.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.kku.edu.tr/"],
    name: "Kirikkale University",
    alpha_two_code: "TR",
    domains: ["kku.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.konya.edu.tr/"],
    name: "Necmettin Erbakan University",
    alpha_two_code: "TR",
    domains: ["konya.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.kou.edu.tr/"],
    name: "Kocaeli University",
    alpha_two_code: "TR",
    domains: ["kou.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ksu.edu.tr/"],
    name: "Kahramanmaras Sütcü Imam University",
    alpha_two_code: "TR",
    domains: ["ksu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ktu.edu.tr/"],
    name: "Karadeniz Technical University",
    alpha_two_code: "TR",
    domains: ["ktu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ku.edu.tr/"],
    name: "Koç University",
    alpha_two_code: "TR",
    domains: ["ku.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.maltepe.edu.tr/"],
    name: "Maltepe University",
    alpha_two_code: "TR",
    domains: ["maltepe.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.marmara.edu.tr/"],
    name: "Marmara University",
    alpha_two_code: "TR",
    domains: ["marmara.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.mersin.edu.tr/"],
    name: "Mersin University",
    alpha_two_code: "TR",
    domains: ["mersin.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.mku.edu.tr/"],
    name: "Mustafa Kemal University",
    alpha_two_code: "TR",
    domains: ["mku.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.msu.edu.tr/"],
    name: "Mimar Sinan University",
    alpha_two_code: "TR",
    domains: ["msu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.mu.edu.tr/"],
    name: "Mugla Sitki Kocman University",
    alpha_two_code: "TR",
    domains: ["mu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ohu.edu.tr/"],
    name: "Omer Halisdemir University",
    alpha_two_code: "TR",
    domains: ["ohu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.nku.edu.tr/"],
    name: "Namik Kemal University",
    alpha_two_code: "TR",
    domains: ["nku.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.metu.edu.tr/"],
    name: "Middle East Technical University",
    alpha_two_code: "TR",
    domains: ["metu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ogu.edu.tr/"],
    name: "Osmangazi University",
    alpha_two_code: "TR",
    domains: ["ogu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.omu.edu.tr/"],
    name: "Ondokuz Mayis University Samsun",
    alpha_two_code: "TR",
    domains: ["omu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.odu.edu.tr"],
    name: "Ordu University",
    alpha_two_code: "TR",
    domains: ["odu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ozyegin.edu.tr/"],
    name: "Ozyegin University",
    alpha_two_code: "TR",
    domains: ["ozyegin.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.pamukkale.edu.tr/"],
    name: "Pamukkale University",
    alpha_two_code: "TR",
    domains: ["pamukkale.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: [
      "http://www.sabanciuniv.edu.tr/",
      "http://www.sabanciuniv.edu/",
    ],
    name: "Sabanci University",
    alpha_two_code: "TR",
    domains: ["sabanciuniv.edu.tr", "sabanciuniv.edu"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.sau.edu.tr/"],
    name: "Sakarya University",
    alpha_two_code: "TR",
    domains: ["sau.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.sdu.edu.tr/"],
    name: "Suleyman Demirel University",
    alpha_two_code: "TR",
    domains: ["sdu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.sehir.edu.tr/"],
    name: "Istanbul Şehir University",
    alpha_two_code: "TR",
    domains: ["sehir.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.selcuk.edu.tr/"],
    name: "Selcuk University",
    alpha_two_code: "TR",
    domains: ["selcuk.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.tau.edu.tr/"],
    name: "Türkisch-Deutsche Universität",
    alpha_two_code: "TR",
    domains: ["tau.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.trakya.edu.tr/"],
    name: "Trakya University",
    alpha_two_code: "TR",
    domains: ["trakya.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ufuk.edu.tr/"],
    name: "Ufuk University",
    alpha_two_code: "TR",
    domains: ["ufuk.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.uludag.edu.tr/"],
    name: "Uludag University",
    alpha_two_code: "TR",
    domains: ["uludag.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.yalova.edu.tr/"],
    name: "Yalova University",
    alpha_two_code: "TR",
    domains: ["yalova.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.yasar.edu.tr/"],
    name: "Yasar University",
    alpha_two_code: "TR",
    domains: ["yasar.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ybu.edu.tr/"],
    name: "Yildirim Beyazit University",
    alpha_two_code: "TR",
    domains: ["ybu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.yeditepe.edu.tr/"],
    name: "Yeditepe University",
    alpha_two_code: "TR",
    domains: ["yeditepe.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.yildiz.edu.tr/"],
    name: "Yildiz Technical University",
    alpha_two_code: "TR",
    domains: ["yildiz.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.yyu.edu.tr/"],
    name: "Yüzüncü Yil (Centennial) University",
    alpha_two_code: "TR",
    domains: ["yyu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.agu.edu.tr/"],
    name: "Abdullah Gul University",
    alpha_two_code: "TR",
    domains: ["agu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.agu.edu.tr/"],
    name: "Adana Science and Technology University",
    alpha_two_code: "TR",
    domains: ["adanabtu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.adiyaman.edu.tr/"],
    name: "Adiyaman University",
    alpha_two_code: "TR",
    domains: ["adiyaman.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.agri.edu.tr/"],
    name: "Agri Ibrahim Cecen University",
    alpha_two_code: "TR",
    domains: ["agri.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.aksaray.edu.tr/"],
    name: "Aksaray University",
    alpha_two_code: "TR",
    domains: ["aksaray.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.alanyaaku.edu.tr/"],
    name: "Alanya Alaaddin Keykubat University",
    alpha_two_code: "TR",
    domains: ["alanyaaku.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.amasya.edu.tr/"],
    name: "Amasya University",
    alpha_two_code: "TR",
    domains: ["amasya.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.asbu.edu.tr/"],
    name: "Ankara Social Science University",
    alpha_two_code: "TR",
    domains: ["asbu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ardahan.edu.tr/"],
    name: "Ardahan University",
    alpha_two_code: "TR",
    domains: ["ardahan.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.artvin.edu.tr/"],
    name: "Artvin Coruh University",
    alpha_two_code: "TR",
    domains: ["artvin.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.bamdirma.edu.tr/"],
    name: "Bandirma ONYEDI Eylul University",
    alpha_two_code: "TR",
    domains: ["bandirma.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.bartin.edu.tr/"],
    name: "Bartin University",
    alpha_two_code: "TR",
    domains: ["bartin.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.batman.edu.tr/"],
    name: "Batman University",
    alpha_two_code: "TR",
    domains: ["batman.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.bayburt.edu.tr/"],
    name: "Bayburt University",
    alpha_two_code: "TR",
    domains: ["bayburt.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.bilecik.edu.tr/"],
    name: "Bilecik Seyh Edebali University",
    alpha_two_code: "TR",
    domains: ["bilecik.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.bingol.edu.tr/"],
    name: "Bingol University",
    alpha_two_code: "TR",
    domains: ["bingol.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.beu.edu.tr/"],
    name: "Bitlis Eren University",
    alpha_two_code: "TR",
    domains: ["beu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.bozok.edu.tr/"],
    name: "Bozok University",
    alpha_two_code: "TR",
    domains: ["bozok.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.btu.edu.tr/"],
    name: "Bursa Tecnical University",
    alpha_two_code: "TR",
    domains: ["btu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.karatekin.edu.tr/"],
    name: "Cankiri karatekin University",
    alpha_two_code: "TR",
    domains: ["karatekin.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.duzce.edu.tr/"],
    name: "Duzce University",
    alpha_two_code: "TR",
    domains: ["duzce.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.erzincan.edu.tr/"],
    name: "Erzincan University",
    alpha_two_code: "TR",
    domains: ["erzincan.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.erzurum.edu.tr/"],
    name: "Erzurum Tecnical University",
    alpha_two_code: "TR",
    domains: ["erzurum.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.gtu.edu.tr/"],
    name: "Gebze Tecnical University",
    alpha_two_code: "TR",
    domains: ["gtu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.gata.edu.tr/"],
    name: "Gulhane military medical Academy",
    alpha_two_code: "TR",
    domains: ["gata.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.gumushane.edu.tr/"],
    name: "Gumushane University",
    alpha_two_code: "TR",
    domains: ["gumushane.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.hakkari.edu.tr/"],
    name: "Hakkari University",
    alpha_two_code: "TR",
    domains: ["hakkari.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.hho.edu.tr/"],
    name: "Air Force Academy",
    alpha_two_code: "TR",
    domains: ["hho.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.hitit.edu.tr/"],
    name: "Hitit University",
    alpha_two_code: "TR",
    domains: ["hitit.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.igdir.edu.tr/"],
    name: "Igdir University",
    alpha_two_code: "TR",
    domains: ["igdir.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.iste.edu.tr/"],
    name: "Iskenderun Tecnical University",
    alpha_two_code: "TR",
    domains: ["iste.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.medeniyet.edu.tr/"],
    name: "Istanbul Medeniyet University",
    alpha_two_code: "TR",
    domains: ["medeniyet.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.istanbul.edu.tr/"],
    name: "Istanbul University",
    alpha_two_code: "TR",
    domains: ["istanbul.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ikc.edu.tr/"],
    name: "Izmir Katip celebi University",
    alpha_two_code: "TR",
    domains: ["ikc.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.karabuk.edu.tr/"],
    name: "Karabuk University",
    alpha_two_code: "TR",
    domains: ["karabuk.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.kmu.edu.tr/"],
    name: "karamanoglu mehmet bey University",
    alpha_two_code: "TR",
    domains: ["kmu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.kastamonu.edu.tr/"],
    name: "Kastamonu University",
    alpha_two_code: "TR",
    domains: ["kastamonu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.kirklareli.edu.tr/"],
    name: "Kirklareli University",
    alpha_two_code: "TR",
    domains: ["kirklareli.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.artuklu.edu.tr/"],
    name: "Mardin Artuklu University",
    alpha_two_code: "TR",
    domains: ["artuklu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.mehmetakif.edu.tr/"],
    name: "Mehmet Akif Ersoy University",
    alpha_two_code: "TR",
    domains: ["mehmetakif.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.msgsu.edu.tr/"],
    name: "Mimar Sinan Fine Arts University",
    alpha_two_code: "TR",
    domains: ["msgsu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.alparslan.edu.tr/"],
    name: "Mus Alparslan University",
    alpha_two_code: "TR",
    domains: ["alparslan.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.nevsehir.edu.tr/"],
    name: "Nevsehir Haci Bektas Veli University",
    alpha_two_code: "TR",
    domains: ["nevsehir.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.osmaniye.edu.tr/"],
    name: "Osmaniye Korkut Ata University",
    alpha_two_code: "TR",
    domains: ["osmaniye.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.erdogan.edu.tr/"],
    name: "Recep Tayip Erdogan University",
    alpha_two_code: "TR",
    domains: ["erdogan.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.siirt.edu.tr/"],
    name: "Siirt University",
    alpha_two_code: "TR",
    domains: ["siirt.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.sinop.edu.tr/"],
    name: "Sinop University",
    alpha_two_code: "TR",
    domains: ["sinop.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.sirnak.edu.tr/"],
    name: "Sirnak University",
    alpha_two_code: "TR",
    domains: ["sirnak.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.tunceli.edu.tr/"],
    name: "Tunceli University",
    alpha_two_code: "TR",
    domains: ["tunceli.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.sbu.edu.tr/"],
    name: "Health Sciences University",
    alpha_two_code: "TR",
    domains: ["sbu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.usak.edu.tr/"],
    name: "Usak University",
    alpha_two_code: "TR",
    domains: ["usak.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.beun.edu.tr/"],
    name: "Bulent Ecevit University",
    alpha_two_code: "TR",
    domains: ["beun.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.acibadem.edu.tr/"],
    name: "Acibadem University",
    alpha_two_code: "TR",
    domains: ["acibadem.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ahap.edu.tr/"],
    name: "Alanya Hamdullah Emin Pasa University",
    alpha_two_code: "TR",
    domains: ["ahap.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.avrasya.edu.tr/"],
    name: "Avrasya University",
    alpha_two_code: "TR",
    domains: ["avrasya.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.bezmialem.edu.tr/"],
    name: "Bezmialem Vakif University",
    alpha_two_code: "TR",
    domains: ["bezmialem.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.biruni.edu.tr/"],
    name: "Biruni University",
    alpha_two_code: "TR",
    domains: ["biruni.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.fatihsultan.edu.tr/"],
    name: "Fatih Sultan Mehmet University",
    alpha_two_code: "TR",
    domains: ["fatihsultan.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.gedik.edu.tr/"],
    name: "Gedik University",
    alpha_two_code: "TR",
    domains: ["gedik.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.hku.edu.tr/"],
    name: "Hasan Kalyoncu University",
    alpha_two_code: "TR",
    domains: ["hku.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.29mayis.edu.tr/"],
    name: "Istanbul 29Mayis  University",
    alpha_two_code: "TR",
    domains: ["29mayis.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.aydin.edu.tr/"],
    name: "Istanbul Aydin University",
    alpha_two_code: "TR",
    domains: ["aydin.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.esenyurt.edu.tr/"],
    name: "Istanbul Esenyurt University",
    alpha_two_code: "TR",
    domains: ["esenyurt.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.gelisim.edu.tr/"],
    name: "Istanbul Gelisim University",
    alpha_two_code: "TR",
    domains: ["gelisim.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.kemerburgaz.edu.tr/"],
    name: "Istanbul Kemerburgaz  University",
    alpha_two_code: "TR",
    domains: ["kemerburgaz.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.medipol.edu.tr/"],
    name: "Istanbul Medipol University",
    alpha_two_code: "TR",
    domains: ["medipol.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.rumeli.edu.tr/"],
    name: "Istanbul Rumeli University",
    alpha_two_code: "TR",
    domains: ["rumeli.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.iszu.edu.tr/"],
    name: "Istanbul Sabahattin Zaim University",
    alpha_two_code: "TR",
    domains: ["iszu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ieu.edu.tr/"],
    name: "Izmir Economy University",
    alpha_two_code: "TR",
    domains: ["ieu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.karatay.edu.tr/"],
    name: "Karatay University",
    alpha_two_code: "TR",
    domains: ["karatay.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.gidatarim.edu.tr/"],
    name: "Konya Gida Tarim University",
    alpha_two_code: "TR",
    domains: ["gidatarim.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.mef.edu.tr/"],
    name: "MEF University",
    alpha_two_code: "TR",
    domains: ["mef.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.nisantasi.edu.tr/"],
    name: "Nisantasi University",
    alpha_two_code: "TR",
    domains: ["nisantasi.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.nny.edu.tr/"],
    name: "Nuh Naci Yazgan University",
    alpha_two_code: "TR",
    domains: ["nny.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.okan.edu.tr/"],
    name: "Okan University",
    alpha_two_code: "TR",
    domains: ["okan.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.pirireis.edu.tr/"],
    name: "Piri Reis University",
    alpha_two_code: "TR",
    domains: ["pirireis.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.sanko.edu.tr/"],
    name: "Sanko University",
    alpha_two_code: "TR",
    domains: ["sanko.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.tedu.edu.tr/"],
    name: "TED University",
    alpha_two_code: "TR",
    domains: ["tedu.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.toros.edu.tr/"],
    name: "Toros University",
    alpha_two_code: "TR",
    domains: ["toros.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.thk.edu.tr/"],
    name: "Turkish Aeronautical Association University",
    alpha_two_code: "TR",
    domains: ["thk.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.antalya.edu.tr/"],
    name: "Antalya international University",
    alpha_two_code: "TR",
    domains: ["antalya.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.uskudar.edu.tr/"],
    name: "Uskudar University",
    alpha_two_code: "TR",
    domains: ["uskudar.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.yeniyuzyil.edu.tr/"],
    name: "Yeni Yuzyil University",
    alpha_two_code: "TR",
    domains: ["yeniyuzyil.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.yuksekihtisasuniversitesi.edu.tr/"],
    name: "Yuksek ihtisas University",
    alpha_two_code: "TR",
    domains: ["yuksekihtisasuniversitesi.edu.tr"],
    country: "Turkey",
  },
  {
    web_pages: ["http://www.ktun.edu.tr/"],
    name: "Konya Technical University",
    alpha_two_code: "TR",
    domains: ["ktun.edu.tr"],
    country: "Turkey",
  },
];
